# Generated by savvy: do not edit by hand
#
# Note:
#   This wrapper file is named as `000-wrappers.R` so that this file is loaded
#   first, which allows users to override the functions defined here (e.g., a
#   print() method for an enum).

#' @useDynLib savvyMatrixExamples, .registration = TRUE
#' @keywords internal
NULL

# Check class and extract the external pointer embedded in the environment
.savvy_extract_ptr <- function(e, class) {
  if(is.null(e)) {
    return(NULL)
  }

  if(inherits(e, class)) {
    e$.ptr
  } else {
    msg <- paste0("Expected ", class, ", got ", class(e)[1])
    stop(msg, call. = FALSE)
  }
}

# Prohibit modifying environments

#' @export
`$<-.savvy_savvyMatrixExamples__sealed` <- function(x, name, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`[[<-.savvy_savvyMatrixExamples__sealed` <- function(x, i, value) {
  class <- gsub("__bundle$", "", class(x)[1])
  stop(class, " cannot be modified", call. = FALSE)
}

#' @export
`ndarray_input` <- function(`x`) {
  invisible(.Call(savvy_ndarray_input__impl, `x`))
}

#' @export
`ndarray_output` <- function() {
  .Call(savvy_ndarray_output__impl)
}

#' @export
`nalgebra_input` <- function(`x`) {
  invisible(.Call(savvy_nalgebra_input__impl, `x`))
}

#' @export
`nalgebra_output` <- function() {
  .Call(savvy_nalgebra_output__impl)
}

#' @export
`glam_input` <- function(`x`) {
  invisible(.Call(savvy_glam_input__impl, `x`))
}

#' @export
`glam_output` <- function() {
  .Call(savvy_glam_output__impl)
}


